# Generated by Django 5.0.6 on 2024-09-14 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Package',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('package_type', models.CharField(default='', max_length=100)),
                ('package_price', models.CharField(default='', max_length=100)),
                ('package_facility_1', models.CharField(default='', max_length=100)),
                ('package_facility_2', models.CharField(default='', max_length=100)),
                ('package_facility_3', models.CharField(default='', max_length=100)),
                ('package_facility_4', models.CharField(default='', max_length=100)),
                ('package_facility_5', models.CharField(default='', max_length=100)),
                ('package_img', models.FileField(blank=True, default='', max_length=250, null=True, upload_to='about/')),
            ],
        ),
    ]
