# Generated by Django 5.0.6 on 2024-09-14 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='gallery',
            old_name='gallery_img',
            new_name='gallery_img_1',
        ),
        migrations.AddField(
            model_name='gallery',
            name='gallery_img_2',
            field=models.FileField(blank=True, default='', max_length=250, null=True, upload_to='about/'),
        ),
    ]
