# Generated by Django 5.0.6 on 2024-09-14 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('our_class', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Class_Type',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('class_type', models.CharField(default='', max_length=100)),
                ('class_price', models.CharField(default='', max_length=100)),
                ('class_des', models.TextField()),
                ('class_type_img', models.FileField(blank=True, default='', max_length=250, null=True, upload_to='about/')),
            ],
        ),
    ]
