# Generated by Django 5.0.6 on 2024-09-12 09:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='service',
            old_name='serive_des',
            new_name='service_des',
        ),
    ]
