# Generated by Django 5.0.6 on 2024-09-12 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0002_rename_serive_des_service_service_des'),
    ]

    operations = [
        migrations.CreateModel(
            name='Service_type',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_type', models.CharField(default='', max_length=100)),
                ('service_type_des', models.TextField()),
            ],
        ),
    ]
