# Generated by Django 5.0.6 on 2024-09-14 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Table',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.CharField(default='', max_length=15)),
                ('timing', models.CharField(default='', max_length=15)),
                ('duration', models.IntegerField(default='', max_length=10)),
                ('room_no', models.IntegerField(default='', max_length=10)),
            ],
        ),
    ]
