# Generated by Django 5.0.6 on 2024-09-14 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('time_table', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='table',
            name='timing',
            field=models.TimeField(default='', max_length=15),
        ),
    ]
