# Generated by Django 5.0.6 on 2024-09-14 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('time_table', '0002_alter_table_timing'),
    ]

    operations = [
        migrations.AlterField(
            model_name='table',
            name='duration',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='table',
            name='room_no',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='table',
            name='timing',
            field=models.TimeField(),
        ),
    ]
