# Generated by Django 5.0.6 on 2024-09-14 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Training',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('training_heading', models.CharField(default='', max_length=100)),
                ('training_des', models.TextField()),
                ('training_img', models.FileField(blank=True, default='', max_length=250, null=True, upload_to='about/')),
            ],
        ),
    ]
